version: "3"

volumes:
  workspace:
    name: workspace

services:
  scheduling:
    build: .
    environment:
      - MONGO_CONNECTION_STRING=mongodb:27017/agenda
      - TEMP_DIR=/workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/workspace
    ports:
      - 3000:3000
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"