version: "3"

volumes:
  workspace:
    name: workspace

services:
  scheduling:
    build: .
    environment:
      - TEMP_DIR=/workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/workspace
    ports:
      - 3000:3000
